"""Add received emails model

Revision ID: 4224d59394a9
Revises: e3357026e75a
Create Date: 2026-01-23 06:15:42.460178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4224d59394a9'
down_revision = 'e3357026e75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('received_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=100), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('uid', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    with op.batch_alter_table('received_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_received_emails_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_received_emails_sender_email'), ['sender_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_received_emails_sender_email'))
        batch_op.drop_index(batch_op.f('ix_received_emails_received_at'))

    op.drop_table('received_emails')
    # ### end Alembic commands ###
